// js/lang.js
// UECS Multi-Language Dictionary

const translations = {
  en: {
    nav_cmd_center: "Command Center",
    nav_erm_numbers: "Emergency Numbers",
    nav_live_map: "Live Map",
    nav_how_it_works: "How It Works",
    nav_about: "About",
    nav_admin_portal: "Admin Portal",
    dashboard_title: "Command Center Dashboard",
    dashboard_subtitle: "Real-time overview of active, pending, and resolved incidents across all divisions.",
    mrt_title: "My Emergency Report",
    mrt_type_label: "Type:",
    mrt_status_label: "Status:",
    mrt_eta_label: "ETA:",
    mrt_location_label: "Location:",
    mrt_syncing: "Syncing…",
    dont_panic_help: "Don't Panic — Help is on the way",
    stat_active_incidents: "Active Incidents",
    stat_active_trend: "-12% vs last hour",
    stat_units_deployed: "Units Deployed",
    stat_units_trend: "Updating live",
    stat_resolved_today: "Resolved Today",
    stat_resolved_trend: "Steady flow",
    stat_system_status: "System Status",
    stat_system_optimal: "Optimal",
    stat_system_trend: "All subsystems running natively",
    helplines_title: "Emergency Helpline Numbers",
    helplines_subtitle: "Official Indian emergency contact numbers — saved and managed in real-time by the command authority.",
    hf_all: "All",
    hf_police: "Police",
    hf_fire: "Fire",
    hf_medical: "Medical",
    hf_disaster: "Disaster",
    hf_general: "General",
    map_title: "Live Coordination Map",
    map_subtitle: "Visualizing team tracking and incident severity in real-time. (Simulated)",
    leg_fire: "Fire / Critical",
    leg_police: "Police / Security",
    leg_medical: "Medical / EMS",
    how_title: "How UECS Works",
    how_subtitle: "A streamlined process to drastically reduce response times and avoid resource duplication.",
    step1_title: "1. Report",
    step1_desc: "User signals an emergency with guaranteed location pinning.",
    step2_title: "2. Allocate",
    step2_desc: "System prioritizes incident severity and assigns cross-agency teams.",
    step3_title: "3. Coordinate",
    step3_desc: "Police, Fire, and Medical share a unified real-time communication line.",
    step4_title: "4. Resolve",
    step4_desc: "Command tracks teams until the situation is safely secured.",
    feat_title: "Core System Features",
    about_prob_title: "The Problem: Disconnected Response",
    about_prob_desc: "During large-scale disasters, the lack of a unified command center results in chaotic responses, dangerous duplication of efforts, and delayed critical care.",
    about_sol_title: "The Solution / UECS",
    about_sol_desc: "UECS breaks down the silos. By merging all real-time incident tracking, dispatch communication, and resource allocation into a single unified platform, we create an impenetrable safety net.",
    about_obj_title: "System Objectives",
    modal_fast_report: "FAST REPORT",
    modal_gps_subtitle: "Auto-detecting exact coordinates...",
    modal_gps_loading: "Establishing secure GPS link",
    modal_type_title: "Select Emergency Nature",
    modal_btn_police: "Police / Security",
    modal_btn_fire: "Fire / Rescue",
    modal_btn_medical: "Medical / EMS",
    modal_success_title: "Report Submitted!",
    modal_success_desc1: "Your emergency report has been received by the UECS command centre.",
    modal_success_desc2_1: "Nearest",
    modal_success_desc2_2: "are being dispatched.",
    modal_eta_val: "Estimated arrival:",
    modal_eta_mins: "minutes",
    modal_track_hint: "We'll track your report status below once you close this window.",
    modal_btn_ok: "OK, Got it — Track My Report"
  },
  hi: {
    nav_cmd_center: "नियंत्रण केंद्र",
    nav_erm_numbers: "आपातकालीन नंबर",
    nav_live_map: "लाइव नक्शा",
    nav_how_it_works: "यह कैसे काम करता है",
    nav_about: "बारे में",
    nav_admin_portal: "एडमिन पोर्टल",
    dashboard_title: "कमांड सेंटर डैशबोर्ड",
    dashboard_subtitle: "सभी डिवीजनों में सक्रिय, लंबित और हल की गई घटनाओं का रीयल-टाइम अवलोकन।",
    mrt_title: "मेरी आपातकालीन रिपोर्ट",
    mrt_type_label: "प्रकार:",
    mrt_status_label: "स्थिति:",
    mrt_eta_label: "समय (ETA):",
    mrt_location_label: "स्थान:",
    mrt_syncing: "सिंक हो रहा है…",
    dont_panic_help: "घबराएं नहीं — मदद रास्ते में है",
    stat_active_incidents: "सक्रिय घटनाएं",
    stat_active_trend: "-12% पिछले घंटे से",
    stat_units_deployed: "तैनात इकाइयां",
    stat_units_trend: "लाइव अपडेट हो रहा है",
    stat_resolved_today: "आज हल की गई",
    stat_resolved_trend: "लगातार प्रगति",
    stat_system_status: "सिस्टम की स्थिति",
    stat_system_optimal: "बेहतरीन",
    stat_system_trend: "सभी सबसिस्टम सही चल रहे हैं",
    helplines_title: "आपातकालीन नंबर",
    helplines_subtitle: "आधिकारिक भारतीय हेल्पलाइन — कमांड द्वारा प्रबंधित।",
    hf_all: "सभी",
    hf_police: "पुलिस",
    hf_fire: "आग",
    hf_medical: "मेडिकल",
    hf_disaster: "आपदा",
    hf_general: "सामान्य",
    map_title: "लाइव समन्वय नक्शा",
    map_subtitle: "टीम और घटनाओं का रीयल-टाइम विज़ुअलाइज़ेशन।",
    leg_fire: "आग / गंभीर",
    leg_police: "पुलिस / सुरक्षा",
    leg_medical: "मेडिकल / एम्बुलेंस",
    how_title: "UECS कैसे काम करता है",
    how_subtitle: "प्रतिक्रिया समय कम करने और संसाधनों को बचाने की प्रक्रिया।",
    step1_title: "1. रिपोर्ट",
    step1_desc: "जीपीएस के साथ आपात स्थिति की रिपोर्ट करें।",
    step2_title: "2. आबंटन",
    step2_desc: "सिस्टम गंभीरता के अनुसार टीम नियुक्त करता है।",
    step3_title: "3. समन्वय",
    step3_desc: "पुलिस, फायर और मेडिकल एक साथ संपर्क में।",
    step4_title: "4. समाधान",
    step4_desc: "जब तक स्थिति सुरक्षित नहीं होती, टीम की निगरानी।",
    feat_title: "मुख्य विशेषताएँ",
    about_prob_title: "समस्या",
    about_prob_desc: "कमांड सेंटर न होने से देरी और भ्रम होता है।",
    about_sol_title: "समाधान / UECS",
    about_sol_desc: "UECS सभी एजेंसियों को एक मजबूत डिजिटल सुरक्षा जाल में जोड़ता है।",
    about_obj_title: "सिस्टम के उद्देश्य",
    modal_fast_report: "त्वरित रिपोर्ट",
    modal_gps_subtitle: "सटीक लोकेशन प्राप्त हो रही है...",
    modal_gps_loading: "सुरक्षित जीपीएस लिंक स्थापित हो रहा है",
    modal_type_title: "आपातकाल का प्रकार चुनें",
    modal_btn_police: "पुलिस / सुरक्षा",
    modal_btn_fire: "आग / बचाव",
    modal_btn_medical: "मेडिकल / एम्बुलेंस",
    modal_success_title: "रिपोर्ट भेज दी गई!",
    modal_success_desc1: "आपकी आपातकालीन रिपोर्ट कमांड सेंटर को मिल गई है।",
    modal_success_desc2_1: "निकटतम",
    modal_success_desc2_2: "इकाइयों को भेजा जा रहा है।",
    modal_eta_val: "अनुमानित समय:",
    modal_eta_mins: "मिनट",
    modal_track_hint: "विंडो बंद करने पर नीचे अपनी रिपोर्ट ट्रैक करें।",
    modal_btn_ok: "ठीक है — मेरी रिपोर्ट ट्रैक करें"
  },
  mr: {
    nav_cmd_center: "नियंत्रण कक्ष",
    nav_erm_numbers: "आपत्कालीन क्रमांक",
    nav_live_map: "थेट नकाशा",
    nav_how_it_works: "हे कसे कार्य करते",
    nav_about: "माहिती",
    nav_admin_portal: "डॅशबोर्ड (प्रशासक)",
    dashboard_title: "कमांड सेंटर डॅशबोर्ड",
    dashboard_subtitle: "सक्रिय आणि सोडवलेल्या घटनांचा रिअल-टाइम आढावा.",
    mrt_title: "माझा आपत्कालीन अहवाल",
    mrt_type_label: "प्रकार:",
    mrt_status_label: "स्थिती:",
    mrt_eta_label: "वेळ:",
    mrt_location_label: "स्थान:",
    mrt_syncing: "सिंक होत आहे…",
    dont_panic_help: "घाबरू नका — मदत येत आहे",
    stat_active_incidents: "सक्रिय घटना",
    stat_active_trend: "गेल्या तासाच्या तुलनेत -12%",
    stat_units_deployed: "तैनात युनिट्स",
    stat_units_trend: "थेट अपडेट होत आहे",
    stat_resolved_today: "आज सोडवलेल्या",
    stat_resolved_trend: "सतत प्रगती",
    stat_system_status: "सिस्टम स्थिती",
    stat_system_optimal: "उत्तम",
    stat_system_trend: "सर्व सिस्टिम्स सुरळीत आहेत",
    helplines_title: "आपत्कालीन क्रमांक",
    helplines_subtitle: "अधिकृत हेल्पलाइन भारतासाठी.",
    hf_all: "सर्व",
    hf_police: "पोलीस",
    hf_fire: "आग",
    hf_medical: "वैद्यकीय",
    hf_disaster: "आपत्ती",
    hf_general: "किरकोळ",
    map_title: "थेट नकाशा नियंत्रण",
    map_subtitle: "थेट घटना आणि टीमची हालचाल.",
    leg_fire: "आग / गंभीर",
    leg_police: "पोलीस / सुरक्षा",
    leg_medical: "वैद्यकीय / एम्ब्युलन्स",
    how_title: "UECS कसे कार्य करते",
    how_subtitle: "थेट नियंत्रण सोपे आणि जलद करते.",
    step1_title: "1. अहवाल द्या",
    step1_desc: "जीपीएससह सुरक्षित अहवाल द्या.",
    step2_title: "2. वेळेवर वाटप",
    step2_desc: "सिस्टम त्वरित उपयुक्त टीम पाठवते.",
    step3_title: "3. समन्वय",
    step3_desc: "पोलीस, फायर आणि वैद्यकीय टीम एकत्र येतात.",
    step4_title: "4. उपाय",
    step4_desc: "परिस्थिती सुरक्षित होईपर्यंत लक्ष ठेवले जाते.",
    feat_title: "मुख्य वैशिष्ट्ये",
    about_prob_title: "मुख्य समस्या",
    about_prob_desc: "सुयोग्य संवाद नसल्याने मदत पोहोचायला उशीर होतो.",
    about_sol_title: "UECS चा उपाय",
    about_sol_desc: "UECS सगळ्यांना एक मजबूत डिजिटल सुरक्षेत जोडते.",
    about_obj_title: "उद्दिष्ट्ये",
    modal_fast_report: "त्वरित अहवाल",
    modal_gps_subtitle: "अचूक लोकेशन मिळवत आहोत...",
    modal_gps_loading: "सुरक्षित जीपीएस लिंक सुरु आहे",
    modal_type_title: "आपत्कालीन प्रकार निवडा",
    modal_btn_police: "पोलीस / सुरक्षा",
    modal_btn_fire: "आग / बचाव",
    modal_btn_medical: "वैद्यकीय / रुग्णवाहिका",
    modal_success_title: "अहवाल पाठवला!",
    modal_success_desc1: "तुमचा आपत्कालीन अहवाल कमांड सेंटरला मिळाला आहे.",
    modal_success_desc2_1: "जवळचे",
    modal_success_desc2_2: "युनिट्स रवाना केले जात आहेत.",
    modal_eta_val: "अंदाजे वेळ:",
    modal_eta_mins: "मिनिटे",
    modal_track_hint: "ही विंडो बंद केल्यावर तुमचा अहवाल खाली ट्रॅक करा.",
    modal_btn_ok: "ठीक आहे — ट्रॅक करा"
  },
  gu: {
    nav_cmd_center: "નિયંત્રણ કેન્દ્ર",
    nav_erm_numbers: "ઈમરજન્સી નંબરો",
    nav_live_map: "લાઇવ નકશો",
    nav_how_it_works: "કેવી રીતે કામ કરે છે",
    nav_about: "વિશે",
    nav_admin_portal: "એડમિન પોર્ટલ",
    dashboard_title: "કમાન્ડ સેન્ટર ડેશબોર્ડ",
    dashboard_subtitle: "તમામ વિભાગોમાં સક્રિય અને ઉકેલાયેલી ઘટનાઓનું રિયલ-ટાઇમ કનેક્શન.",
    mrt_title: "મારો રિપોર્ટ",
    mrt_type_label: "પ્રકાર:",
    mrt_status_label: "સ્ટેટસ:",
    mrt_eta_label: "ETA:",
    mrt_location_label: "સ્થાન:",
    mrt_syncing: "અપડેટ થઈ રહ્યું છે…",
    dont_panic_help: "ગભરાશો નહીં — મદદ આવી રહી છે",
    stat_active_incidents: "સક્રિય ઘટનાઓ",
    stat_active_trend: "-12% છેલ્લા એક કલાકમાં",
    stat_units_deployed: "તૈનાત યુનિટ્સ",
    stat_units_trend: "લાઈવ અપડેટ",
    stat_resolved_today: "ઉકેલાયેલી (આજે)",
    stat_resolved_trend: "સ્થિર",
    stat_system_status: "સિસ્ટમ સ્ટેટસ",
    stat_system_optimal: "શ્રેષ્ઠ",
    stat_system_trend: "બધું બરાબર ચાલી રહ્યું છે",
    helplines_title: "ઈમરજન્સી નંબરો",
    helplines_subtitle: "ભારતીય ઈમરજન્સી હેલ્પલાઈન.",
    hf_all: "બધા",
    hf_police: "પોલીસ",
    hf_fire: "આગ",
    hf_medical: "મેડિકલ",
    hf_disaster: "આપત્તિ",
    hf_general: "સાધારણ",
    map_title: "લાઇવ નકશો",
    map_subtitle: "ટીમનું રિયલ-ટાઇમ લોકેશન.",
    leg_fire: "આગ",
    leg_police: "પોલીસ",
    leg_medical: "મેડિકલ",
    how_title: "UECS કેવી રીતે કામ કરે છે",
    how_subtitle: "મદદ પહોંચાડવાની ઝડપી પ્રક્રિયા.",
    step1_title: "1. જાણ કરો",
    step1_desc: "જીપીએસ સચોટ લોકેશન આપે છે.",
    step2_title: "2. ફાળવણી",
    step2_desc: "જોખમ મુજબ ટીમ મોકલવામાં આવે છે.",
    step3_title: "3. કામગીરી",
    step3_desc: "પોલીસ, ફાયર અને મેડિકલ વચ્ચે સતત સંપર્ક.",
    step4_title: "4. ઉકેલ",
    step4_desc: "વ્યક્તિ સુરક્ષિત ના થાય ત્યાં સુધી નજર રખાય છે.",
    feat_title: "મુખ્ય વિશેષતાઓ",
    about_prob_title: "સમસ્યા",
    about_prob_desc: "નિયંત્રણના અભાવના કારણે મદદ મોડી પહોંચે છે.",
    about_sol_title: "ઉકેલ (UECS)",
    about_sol_desc: "આ સિસ્ટમ કામગીરીને ઝડપી અને સચોટ બનાવે છે.",
    about_obj_title: "ધ્યેય",
    modal_fast_report: "ઝડપી જાણ",
    modal_gps_subtitle: "સચોટ લોકેશન શોધી રહ્યા છીએ...",
    modal_gps_loading: "GPS લિંક જોડાઈ રહી છે",
    modal_type_title: "ઈમરજન્સીનો પ્રકાર પસંદ કરો",
    modal_btn_police: "પોલીસ / સુરક્ષા",
    modal_btn_fire: "આગ / બચાવ",
    modal_btn_medical: "મેડિકલ / એમ્બ્યુલન્સ",
    modal_success_title: "રિપોર્ટ મોકલાઈ ગયો!",
    modal_success_desc1: "તમારો મેસેજ કમાન્ડ સેન્ટરમાં મળી ગયો છે.",
    modal_success_desc2_1: "નજીકની",
    modal_success_desc2_2: "ટીમને મોકલવામાં આવી રહી છે.",
    modal_eta_val: "અંદાજિત સમય:",
    modal_eta_mins: "મિનિટ",
    modal_track_hint: "આ વિન્ડો બંધ કર્યા પછી તમારો રિપોર્ટ ટ્રેક કરો.",
    modal_btn_ok: "ઓકે — રિપોર્ટ ટ્રેક કરો"
  }
};

window.i18nTranslations = translations;
